spring:
  datasource:
    url: jdbc:mysql://172.16.79.42:3306/activiti?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: Sign@2020
    driver-class-name: com.mysql.cj.jdbc.Driver
